version: '2'
services:
  php:
    image: https://github.com/tarisiddiq/tarisiddiq.github.io
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
    links:
      - db

  db:
    image: prayoga03/mysql-tcc
    volumes:
     - ./db:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=tari